version: "3.9"

services:
  fastapi:
    build:
      context: .                # Build from the directory containing Dockerfile
      dockerfile: Dockerfile    # Use the Dockerfile above
    ports:
      - "8000:8000"             # Map host port 8000 to container port 8000
    volumes:
      - ./uploads:/app/uploads  # Mount uploads/ for persistent file storage (if used)
    environment:
      - PYTHONUNBUFFERED=1      # Ensure logs are unbuffered for real-time output
    restart: unless-stopped     # Restart unless manually stopped