services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: [ "/bin/sh", "-c" ]
    command: "certbot certonly --webroot --webroot-path=/var/www/certbot --email aadityaa2606@gmail.com --agree-tos --no-eff-email --force-renewal -d autis-backend.aadinagarajan.com"

networks:
  app-network:
