services:
  fastapi:
    build:
      context: .                # Build from the current directory
      dockerfile: Dockerfile    # Use the Dockerfile
    ports:
      - "8005:8005"             # Map host port 8005 to container port 8005
    restart: unless-stopped     # Restart unless manually stopped